services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./:/app/
    command: >
      sh -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - ".env"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.admin"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "5555:80"